obj-$(CONFIG_NET_RALINK) += ralink-fe.o

ralink-fe-y := ralink_fe.o

ralink-fe-$(CONFIG_RALINK_FE_PPE) += ra_ppe.o
ralink-fe-$(CONFIG_RALINK_FE_PPE) += ra_ppe_offload.o
ralink-fe-$(CONFIG_RALINK_FE_PPE) += ra_ppe_v1.o
ralink-fe-$(CONFIG_RALINK_FE_PPE) += ra_ppe_v1_offload.o
